version: '3.3'

services:
  rabbitmq:
     image: rabbitmq:3.11-management
     environment:
       - RABBITMQ_DEFAULT_USER=rabbitmq_user
       - RABBITMQ_DEFAULT_PASS=rabbitmq_pass
     ports:
       - "5672:5672"
       - "15672:15672"
